# permissions for end users to edit pools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pool-editor-role
rules:
- apiGroups:
  - fortiadc.ouest-france.fr
  resources:
  - pools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fortiadc.ouest-france.fr
  resources:
  - pools/status
  verbs:
  - get
