# permissions for end users to view realservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: realserver-viewer-role
rules:
- apiGroups:
  - fortiadc.ouest-france.fr
  resources:
  - realservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fortiadc.ouest-france.fr
  resources:
  - realservers/status
  verbs:
  - get
