apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fortiadc-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  address: "{{ .Values.fortiadc.secret.address }}"
  insecure: "{{ .Values.fortiadc.secret.insecure }}"
  password: "{{ .Values.fortiadc.secret.password }}"
  username: "{{ .Values.fortiadc.secret.username }}"